version: '3.9'

services:
  vigilant-journey:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: development
    image: vigilant-journey 
    container_name: vigilant-journey
    depends_on:
      - vigilant-journey-db
    ports: 
      - "3000:3000"
    volumes: 
      - .:/home/app
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: true
      RAILS_SERVE_STATIC_FILES: true

volumes:
  db_data:
